const jwtServiceConfig = {
  signIn: 'login',
  signUp: 'signup',
  accessToken: 'refresh-token',
  updateUser: 'user/update',
  invitationDetails: 'invitation-details',
  forgotPassword: 'forgot-password',
  resetPassword: 'reset-password',
  logout: 'logout',
  companies: 'companies',
  getGeneralConfiguration: 'get-general-tab-data',
  saveGeneralConfiguration: 'save-general-tab-data',
  getEmailConguration: 'emailconfigurations/view',
  saveEmailConguration: 'emailconfigurations/save',
  getIpConfiguration: 'ip-configurations',
  saveIpConfiguration: 'ip-configurations/save',
  getDowntimeConfiguration: 'ip-downtime-settings',
  saveDowntimeConfiguration: 'ip-downtime-update',
  profile: 'profile',
  updateProfile: 'profile-update',
  saveEmailTemplates: 'email-templates/save',
  updateEmailTemplates: 'email-templates/update',
  getSingleEmailTemplate: 'email-templates/edit',
  getEmailTemplatesFieldData: 'email-templates/add',
  confirmAccountCheck: 'check-auth',
  getMetaTagsConfiguration: 'meta-tags',
  saveMetaTagsConfiguration: 'meta-tags/update',
  getPaymentMethodConfiguration: 'payment-methods',
  savePaymentMethodConfiguration: 'payment-methods/update',
  saveScriptsData: 'scripts/save',
  updateScriptsData: 'scripts/update',
  getSingleScriptData: 'scripts/edit'
};

export default jwtServiceConfig;
