version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-2)
      - BACKEND_REPOSITORY_URI=473524174152.dkr.ecr.us-east-2.amazonaws.com/99ventures-backend-stg
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - FRONTEND_IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $BACKEND_REPOSITORY_URI:latest ./backend
      - docker tag $BACKEND_REPOSITORY_URI:latest $BACKEND_REPOSITORY_URI:$BACKEND_IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $BACKEND_REPOSITORY_URI:latest
      - docker push $BACKEND_REPOSITORY_URI:$BACKEND_IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"backend","imageUri":"%s"}]' $BACKEND_REPOSITORY_URI:$BACKEND_IMAGE_TAG > imagedefinitions.json

artifacts:
    files: imagedefinitions.json