version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 473524174152.dkr.ecr.us-east-2.amazonaws.com
      - FRONTEND_REPOSITORY_URI=473524174152.dkr.ecr.us-east-2.amazonaws.com/99ventures-frontend-stg
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - FRONTEND_IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $FRONTEND_REPOSITORY_URI:latest ./frontend
      - docker tag $FRONTEND_REPOSITORY_URI:latest $FRONTEND_REPOSITORY_URI:$FRONTEND_IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...`
      - docker push $FRONTEND_REPOSITORY_URI:latest
      - docker push $FRONTEND_REPOSITORY_URI:$FRONTEND_IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"frontend","imageUri":"%s"}]' $FRONTEND_REPOSITORY_URI:$FRONTEND_IMAGE_TAG > imagedefinitions-frontend.json

artifacts:
    files: imagedefinitions-frontend.json