version: '3'

networks:
  99Bridge:

services:
  backend:
    container_name: '99-live-node'
    # image: $ECR_REPO_FOR_BACKEND
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 4000:4000
    environment:
      - DB_HOST=$LIVE_MYSQLDB_HOST
      - DB_USER=$LIVE_MYSQLDB_USER
      - DB_PASSWORD=$LIVE_MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$LIVE_MYSQLDB_DATABASE
      - DB_PORT=$LIVE_MYSQLDB_DOCKER_PORT
      - CLIENT_ORIGIN=$LIVE_CLIENT_ORIGIN
      - APP_SECRET=$LIVE_NODE_APP_SECRET
      - S3_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID
      - S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY
      - S3_BUCKET_NAME=$S3_BUCKET_NAME
      - DEFAULT_REGION=$AWS_DEFAULT_REGION
      - CLIENT_API_PUBLIC_URL=$LIVE_CLIENT_API_PUBLIC_URL
      - S3_BUCKET_OBJECT_URL=$S3_BUCKET_OBJECT_URL
      - IP_QUALITY_SCORE_PRIVATE_KEY=$IP_QUALITY_SCORE_PRIVATE_KEY
      - PORT=4000
    networks:
      - 99Bridge
    volumes:
      - ./backend:/usr/src/backend
      - /usr/src/backend/node_modules

  admin:
    depends_on:
      - backend
    container_name: '99-live-react'
    # image: $ECR_REPO_FOR_ADMIN
    restart: always
    build:
      context: ./admin
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_BASE_URL=$LIVE_CLIENT_API_BASE_URL
    ports:
      - 80:80
      - 443:443
    environment: 
      - REACT_APP_API_BASE_URL=$LIVE_CLIENT_API_BASE_URL
    networks:
      - 99Bridge