FROM node:17
WORKDIR /usr/src/frontend
COPY package*.json ./
RUN npm install --legacy-peer-deps
RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache
COPY . .
EXPOSE 8080
CMD [ "npm", "run", "start" ]